### ISSUE TITLE
Are meta searx instances enough visible ?

### ISSUE THREAD

**Issue by dalf** [dalf/searx-stats2#23]
On searx.space, there is this sentence at the top of the front page:

> _See the About section to know how to edit this list or look for the meta searx instances_

Before that the meta searx instances were listed first, then the online instances:
https://github.com/asciimoo/searx/wiki/Searx-instances/aea2f3feaeb3d5998a860b17c25874d2571d52e9

Thumb up: to answer yes.
Thumb down: to answer no.

**Comment by dalf** [comment]
This comment asks for more visibility of the meta searx intances: https://github.com/asciimoo/searx/issues/1853#issuecomment-604775936

**Comment by return42** [comment]
I voted down ..  what we (at the searx project) need is searx.me back or any other reference installation.

Yesterday I asked @ascimoo about searx.me and if there is a chance to see a instance working under this address .. I am still waiting for his answer, but I wouldn't be surprised if it takes a little longer these days. 

BTW the header ..

> Are meta searx instances enough visible ?

and the thumbs ..

> Thumb up if you think the meta searx instances should be listed on the front page.

could be a bit misleading :)

**Comment by MilkManzJourDaddy** [comment]
Unfortunately the very people who need to be on-boarded, e.g. inspired to use Searx instead of Google®, such end-users would never find their way to this repo' & issue. 

People who technologically support i.e. family & friends & clients may not find their way to this repo' & issue either.  Only those who are well aware of Searx and understand that end-users who are told of Searx would just use Google® to search and therefore be pointed to searx.me **which currently offers no DIRECT way for end-users to search or try Searx, so for end-users or even intermediate users, it is a DEAD END.** 

Fully funded projects have on-boarding specislists.  If you cannot think like an end-user, nor have ever tried to on-board an end-user, maybe diagram a flow-chart of the decisions they might make, i.e. being told of a better search tool, ignoring a link to i.e. searx.neocities.org and finding search results pointing to searx.me , visiting searx.me and not finding a search tool but instead being pointed to things they do not understand asking them to do things orthogonal to and incongruent with their skill set: e.g. "**Brick Wall**".  

They are not going to click-through to searx.space or will not know what to do from there.  If they had a MetaSearx i.e. searx.neocities.org in a `frame` within searx.me , at least they would get a positive-reinforcement and **THEN**, possibly be inspired directly visit and bookmark/favorite searx.neocities.org or get past "new thing fatigue" ( like "Account Fatigue" ) to try and choose an existing Searx instance, or get help setting up one.

**Comment by return42** [comment]
@MilkManzJourDaddy we do not have write access to searx.me, the searx Redirector from neocities.org is closed source and we can't change the "searx" google hits.  The only thing, we can do is asking @asciimoo about searx.me .. this is what I have done .. still waiting about feedback.  And who is responsible for searx.neocities.org .. I don't know, they do not link their sources and I cant find a project side for the redirector ..

**Comment by dalf** [comment]
Possible to do list about meta instances:  
1. At least provide enough metrics in searx-stats2 to automaticaly get an instance list (see https://searx.neocities.org/changelog.html ).
2. On way to deal with meta instance is to include one meta instance in searx.space: most probably it would require some manual entries / tags on each instance : it can be an additional field in https://github.com/dalf/searx-instances
